export const Routes = {
  HOME: "/",
  LOGIN: "/login",
  NEW: "/new",
  ADMIN: "/admin",
  ONBOARDING_PROFILE: "/onboarding/profile",
  ADMIN_DONATIONS: "/admin/donations",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_EDIT: "/admin/edit",
  ADMIN_TIPLINKS: "/admin/tiplink",
  ADMIN_NEW_TIPLINKS: "/admin/tiplink/create",
  ADMIN_KOL_STREAM: "/admin/kol-stream",
  ADMIN_NFT_DISPENSER: "/admin/nft-dispenser",
  ADMIN_NEW_NFT_DISPENSER: "/admin/nft-dispenser/create",
  ADMIN_C_NFT_DISPENSER: "/admin/c-nft-dispenser",
  ADMIN_NEW_C_NFT_DISPENSER: "/admin/c-nft-dispenser/create",
  ADMIN_DISPENSER: "/admin/dispenser",
};
